//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class plibrarydbEntities : DbContext
    {
        public plibrarydbEntities()
            : base("name=plibrarydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Book_status> Book_status { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
    
        public virtual int DeleteBook(Nullable<int> in_book_id)
        {
            var in_book_idParameter = in_book_id.HasValue ?
                new ObjectParameter("in_book_id", in_book_id) :
                new ObjectParameter("in_book_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBook", in_book_idParameter);
        }
    
        public virtual int DeleteLoan(Nullable<int> in_loan_id)
        {
            var in_loan_idParameter = in_loan_id.HasValue ?
                new ObjectParameter("in_loan_id", in_loan_id) :
                new ObjectParameter("in_loan_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLoan", in_loan_idParameter);
        }
    
        public virtual int DeleteReader(Nullable<int> in_reader_id)
        {
            var in_reader_idParameter = in_reader_id.HasValue ?
                new ObjectParameter("in_reader_id", in_reader_id) :
                new ObjectParameter("in_reader_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteReader", in_reader_idParameter);
        }
    
        public virtual ObjectResult<GetAllBooks_Result> GetAllBooks(string in_userid)
        {
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllBooks_Result>("GetAllBooks", in_useridParameter);
        }
    
        public virtual ObjectResult<GetAllLoans_Result> GetAllLoans(string in_userid)
        {
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLoans_Result>("GetAllLoans", in_useridParameter);
        }
    
        public virtual ObjectResult<GetAllReaders_Result> GetAllReaders(string in_userid)
        {
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllReaders_Result>("GetAllReaders", in_useridParameter);
        }
    
        public virtual ObjectResult<GetBookByID_Result> GetBookByID(Nullable<int> in_book_id)
        {
            var in_book_idParameter = in_book_id.HasValue ?
                new ObjectParameter("in_book_id", in_book_id) :
                new ObjectParameter("in_book_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBookByID_Result>("GetBookByID", in_book_idParameter);
        }
    
        public virtual ObjectResult<GetLoanByID_Result> GetLoanByID(Nullable<int> in_loan_id)
        {
            var in_loan_idParameter = in_loan_id.HasValue ?
                new ObjectParameter("in_loan_id", in_loan_id) :
                new ObjectParameter("in_loan_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLoanByID_Result>("GetLoanByID", in_loan_idParameter);
        }
    
        public virtual ObjectResult<GetReaderByID_Result> GetReaderByID(Nullable<int> in_reader_id)
        {
            var in_reader_idParameter = in_reader_id.HasValue ?
                new ObjectParameter("in_reader_id", in_reader_id) :
                new ObjectParameter("in_reader_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReaderByID_Result>("GetReaderByID", in_reader_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> InsertBook(string in_userid, string in_title, string in_genre, Nullable<int> in_publication_year, string in_authors, Nullable<int> in_book_status, string in_cover)
        {
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            var in_titleParameter = in_title != null ?
                new ObjectParameter("in_title", in_title) :
                new ObjectParameter("in_title", typeof(string));
    
            var in_genreParameter = in_genre != null ?
                new ObjectParameter("in_genre", in_genre) :
                new ObjectParameter("in_genre", typeof(string));
    
            var in_publication_yearParameter = in_publication_year.HasValue ?
                new ObjectParameter("in_publication_year", in_publication_year) :
                new ObjectParameter("in_publication_year", typeof(int));
    
            var in_authorsParameter = in_authors != null ?
                new ObjectParameter("in_authors", in_authors) :
                new ObjectParameter("in_authors", typeof(string));
    
            var in_book_statusParameter = in_book_status.HasValue ?
                new ObjectParameter("in_book_status", in_book_status) :
                new ObjectParameter("in_book_status", typeof(int));
    
            var in_coverParameter = in_cover != null ?
                new ObjectParameter("in_cover", in_cover) :
                new ObjectParameter("in_cover", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("InsertBook", in_useridParameter, in_titleParameter, in_genreParameter, in_publication_yearParameter, in_authorsParameter, in_book_statusParameter, in_coverParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> InsertLoan(string in_userid, Nullable<int> in_reader_id, Nullable<int> in_book_id, Nullable<System.DateTime> in_loan_date, Nullable<bool> in_if_closed)
        {
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            var in_reader_idParameter = in_reader_id.HasValue ?
                new ObjectParameter("in_reader_id", in_reader_id) :
                new ObjectParameter("in_reader_id", typeof(int));
    
            var in_book_idParameter = in_book_id.HasValue ?
                new ObjectParameter("in_book_id", in_book_id) :
                new ObjectParameter("in_book_id", typeof(int));
    
            var in_loan_dateParameter = in_loan_date.HasValue ?
                new ObjectParameter("in_loan_date", in_loan_date) :
                new ObjectParameter("in_loan_date", typeof(System.DateTime));
    
            var in_if_closedParameter = in_if_closed.HasValue ?
                new ObjectParameter("in_if_closed", in_if_closed) :
                new ObjectParameter("in_if_closed", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("InsertLoan", in_useridParameter, in_reader_idParameter, in_book_idParameter, in_loan_dateParameter, in_if_closedParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> InsertReader(string in_userid, string in_first_name, string in_last_name, string in_email, Nullable<bool> in_has_book)
        {
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            var in_first_nameParameter = in_first_name != null ?
                new ObjectParameter("in_first_name", in_first_name) :
                new ObjectParameter("in_first_name", typeof(string));
    
            var in_last_nameParameter = in_last_name != null ?
                new ObjectParameter("in_last_name", in_last_name) :
                new ObjectParameter("in_last_name", typeof(string));
    
            var in_emailParameter = in_email != null ?
                new ObjectParameter("in_email", in_email) :
                new ObjectParameter("in_email", typeof(string));
    
            var in_has_bookParameter = in_has_book.HasValue ?
                new ObjectParameter("in_has_book", in_has_book) :
                new ObjectParameter("in_has_book", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("InsertReader", in_useridParameter, in_first_nameParameter, in_last_nameParameter, in_emailParameter, in_has_bookParameter);
        }
    
        public virtual int UpdateBook(Nullable<int> in_book_id, string in_userid, string in_title, string in_genre, Nullable<int> in_publication_year, string in_authors, Nullable<int> in_book_status, string in_cover)
        {
            var in_book_idParameter = in_book_id.HasValue ?
                new ObjectParameter("in_book_id", in_book_id) :
                new ObjectParameter("in_book_id", typeof(int));
    
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            var in_titleParameter = in_title != null ?
                new ObjectParameter("in_title", in_title) :
                new ObjectParameter("in_title", typeof(string));
    
            var in_genreParameter = in_genre != null ?
                new ObjectParameter("in_genre", in_genre) :
                new ObjectParameter("in_genre", typeof(string));
    
            var in_publication_yearParameter = in_publication_year.HasValue ?
                new ObjectParameter("in_publication_year", in_publication_year) :
                new ObjectParameter("in_publication_year", typeof(int));
    
            var in_authorsParameter = in_authors != null ?
                new ObjectParameter("in_authors", in_authors) :
                new ObjectParameter("in_authors", typeof(string));
    
            var in_book_statusParameter = in_book_status.HasValue ?
                new ObjectParameter("in_book_status", in_book_status) :
                new ObjectParameter("in_book_status", typeof(int));
    
            var in_coverParameter = in_cover != null ?
                new ObjectParameter("in_cover", in_cover) :
                new ObjectParameter("in_cover", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBook", in_book_idParameter, in_useridParameter, in_titleParameter, in_genreParameter, in_publication_yearParameter, in_authorsParameter, in_book_statusParameter, in_coverParameter);
        }
    
        public virtual int UpdateLoan(Nullable<int> in_loan_id, string in_userid, Nullable<int> in_reader_id, Nullable<int> in_book_id, Nullable<System.DateTime> in_loan_date, Nullable<bool> in_if_closed)
        {
            var in_loan_idParameter = in_loan_id.HasValue ?
                new ObjectParameter("in_loan_id", in_loan_id) :
                new ObjectParameter("in_loan_id", typeof(int));
    
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            var in_reader_idParameter = in_reader_id.HasValue ?
                new ObjectParameter("in_reader_id", in_reader_id) :
                new ObjectParameter("in_reader_id", typeof(int));
    
            var in_book_idParameter = in_book_id.HasValue ?
                new ObjectParameter("in_book_id", in_book_id) :
                new ObjectParameter("in_book_id", typeof(int));
    
            var in_loan_dateParameter = in_loan_date.HasValue ?
                new ObjectParameter("in_loan_date", in_loan_date) :
                new ObjectParameter("in_loan_date", typeof(System.DateTime));
    
            var in_if_closedParameter = in_if_closed.HasValue ?
                new ObjectParameter("in_if_closed", in_if_closed) :
                new ObjectParameter("in_if_closed", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLoan", in_loan_idParameter, in_useridParameter, in_reader_idParameter, in_book_idParameter, in_loan_dateParameter, in_if_closedParameter);
        }
    
        public virtual int UpdateReader(Nullable<int> in_reader_id, string in_userid, string in_first_name, string in_last_name, string in_email, Nullable<bool> in_has_book)
        {
            var in_reader_idParameter = in_reader_id.HasValue ?
                new ObjectParameter("in_reader_id", in_reader_id) :
                new ObjectParameter("in_reader_id", typeof(int));
    
            var in_useridParameter = in_userid != null ?
                new ObjectParameter("in_userid", in_userid) :
                new ObjectParameter("in_userid", typeof(string));
    
            var in_first_nameParameter = in_first_name != null ?
                new ObjectParameter("in_first_name", in_first_name) :
                new ObjectParameter("in_first_name", typeof(string));
    
            var in_last_nameParameter = in_last_name != null ?
                new ObjectParameter("in_last_name", in_last_name) :
                new ObjectParameter("in_last_name", typeof(string));
    
            var in_emailParameter = in_email != null ?
                new ObjectParameter("in_email", in_email) :
                new ObjectParameter("in_email", typeof(string));
    
            var in_has_bookParameter = in_has_book.HasValue ?
                new ObjectParameter("in_has_book", in_has_book) :
                new ObjectParameter("in_has_book", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReader", in_reader_idParameter, in_useridParameter, in_first_nameParameter, in_last_nameParameter, in_emailParameter, in_has_bookParameter);
        }
    }
}
